spring:
  application:
    name: dungeong

  # DB 연결 정보 (JPA와 Flyway에서 함께 사용)
  datasource:
    url: jdbc:postgresql://localhost:5432/dreamshow_db
    username: dreamshow_user
    password: dsc0524
    driver-class-name: org.postgresql.Driver

  # JPA(Hibernate) 설정
  jpa:
    hibernate:
      # Flyway가 DDL을 관리하므로 Hibernate의 자동 생성/수정 기능은 끈다.
      ddl-auto: none
      # Hibernate가 DB 테이블/컬럼 이름을 자동으로 변경하지 않고, @Table, @Column에 명시된 이름을 '그대로' 사용하도록 강제함
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # 실행된 SQL 쿼리 보기
        show_sql: true
        format_sql: true
        # DB 식별자(테이블/컬럼명)에 항상 따옴표(")를 붙여서 쿼리를 생성하도록 강제함 (PostgreSQL의 대소문자 구분 문제를 해결)
        globally_quoted_identifiers: true
    # OSIV(Open Session In View) 기능 끄기 (성능 최적화)
    open-in-view: false

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/seed

  # AWS S3 연동 설정 (Region 및 Dummy Credentials)
  cloud:
    aws:
      # 실제 자격 증명은 환경 변수나 IAM Role을 통해 주입하는 것이 보안상 안전합니다.
      region:
        static: ap-northeast-2
      credentials:
        access-key: DUMMY_ACCESS_KEY
        secret-key: DUMMY_SECRET_KEY

  # OAuth 설정 파일(application-secret.yml) 포함시키기
  profiles:
    include: secret

  # ==========================================
  # 파일 업로드 용량 제한 설정 (기본값: 파일당 1MB / 요청당 10MB)
  # ==========================================
  servlet:
    multipart:
      # 단일 파일 최대 크기 (예: 200MB)
      max-file-size: 200MB
      # 전체 요청 최대 크기 (파일 여러 개 합친 크기, 예: 200MB)
      max-request-size: 200MB



frontend:
  redirect-url: http://localhost:3000/oauth/callback
  error-url: http://localhost:3000/auth/error